### ISSUE TITLE
/admin/api/posts/ にてcreateした際の挙動が変

### ISSUE THREAD

**Issue by kaave** [ali-inc/dera#5]
レコードは作成されるもののエラーになってます。

以下ログ

```
[error] #PID<0.926.0> running Dera.Endpoint terminated
Server: vgt-phoenix:4000 (http)
Request: POST /admin/api/posts/
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Phoenix.Param not implemented for {:ok, %Dera.Post{__meta__: #Ecto.Schema.Me
tadata<:loaded>, author: #Ecto.Association.NotLoaded<association :author is not loaded>, body: "<h1>ｓｄｇｋｌｈｓｄｇ
</h1><p>ｓｄｇｋｊｈｄｓｇ</p><p>ｄｓｋｊｈｋｆ</p><p><br></p>", category: #Ecto.Association.NotLoaded<association :ca
tegory is not loaded>, category_id: 11, id: 4, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 5, hour: 3, min
ute: 31, month: 1, ms: 0.0, second: 39, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, posts_tags: [%Dera.PostsTag{__meta__: #Ecto.Schema.Metadat
a<:loaded>, id: 7, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 5, hour: 3, minute: 31, month: 1, ms: 0.0,
second: 39, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc
: 0, until: :max}, year: 2016}, post: #Ecto.Association.NotLoaded<association :post is not loaded>, post_id: 4, tag: #
Ecto.Association.NotLoaded<association :tag is not loaded>, tag_id: 1, updated_at: %Timex.DateTime{calendar: :gregorian, day: 5, hour: 3, minute: 31, month: 1, ms: 0.0, second: 39, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from
: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}}, %Dera.PostsTag{__meta__: #Ecto.Sch
ema.Metadata<:loaded>, id: 8, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 5, hour: 3, minute: 31, month: 1
, ms: 0.0, second: 39, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0,
 offset_utc: 0, until: :max}, year: 2016}, post: #Ecto.Association.NotLoaded<association :post is not loaded>, post_id: 4, tag: #Ecto.Association.NotLoaded<association :tag is not loaded>, tag_id: 5, updated_at: %Timex.DateTime{calendar
: :gregorian, day: 5, hour: 3, minute: 31, month: 1, ms: 0.0, second: 39, timezone: %Timex.TimezoneInfo{abbreviation:
"UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}}], published_at: #Ecto.Da
teTime<2016-01-04T02:09:00Z>, pv: nil, status: 3, tags: #Ecto.Association.NotLoaded<association :tags is not loaded>,
thumb: %{file_name: "00_dj_hellfish_-_back_to_the_old_hip_hop_shit_ep-(deathchant58)-vinyl-2009-a.jpg", updated_at: #Ecto.DateTime<2016-01-05T03:31:39Z>}, title: "ｓｄふぉいうｓｄｇ", updated_at: %Timex.DateTime{calendar: :gregorian, da
y: 5, hour: 3, minute: 31, month: 1, ms: 0.0, second: 39, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :mi
n, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, user_id: nil}}
        (phoenix) lib/phoenix/param.ex:130: Phoenix.Param.Any.to_param/1
        (dera) web/router.ex:1: Dera.Router.Helpers.admin_api_post_path/4
        (dera) web/controllers/admin/api/post_controller.ex:22: Dera.Admin.Api.PostController.create/2
        (dera) web/controllers/admin/api/post_controller.ex:1: Dera.Admin.Api.PostController.action/2
        (dera) web/controllers/admin/api/post_controller.ex:1: Dera.Admin.Api.PostController.phoenix_controller_pipeli
ne/2
        (dera) lib/phoenix/router.ex:261: Dera.Router.dispatch/2
        (dera) web/router.ex:1: Dera.Router.do_call/2
        (dera) lib/dera/endpoint.ex:1: Dera.Endpoint.phoenix_pipeline/1
        (dera) lib/plug/debugger.ex:92: Dera.Endpoint."call (overridable 3)"/2
        (dera) lib/phoenix/endpoint/render_errors.ex:34: Dera.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by kaave** [comment]
タイトルをちょっと修正しました。

さっきやったらエラーの種類がかわってたので添付しときます

```
[debug] Processing by Dera.Admin.Api.PostController.create/2
  Parameters: %{"_csrf_token" => "CDc2QRoQIQ8tey0WNDMsYTR2KQARJgAAguOtuULmJ4CgeTC9w/ahZQ==", "post" => %{"body" => "<p
>with Image Post</p><p>with Image Post</p>", "category_id" => "13", "posts_tags" => %{"0" => %{"tag_id" => "1"}, "1" =
> %{"tag_id" => "5"}}, "published_at" => %{"day" => "1", "hour" => "9", "min" => "0", "month" => "1", "year" => "2016"
}, "status" => "2", "thumb" => %Plug.Upload{content_type: "image/jpeg", filename: "www.dotup.jpg", path: "/tmp/plug-14
52/multipart-60941-221262-1"}, "title" => "with image post"}}
  Pipelines: [:api]
warning: casting assocs with cast/4 is deprecated, please use cast_assoc/3 instead
    (ecto) lib/ecto/changeset.ex:417: Ecto.Changeset.do_process_param/8
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (ecto) lib/ecto/changeset.ex:377: Ecto.Changeset.cast/5
[debug] BEGIN [] OK query=1.7ms queue=0.1ms
[debug] INSERT INTO "posts" ("inserted_at", "updated_at", "body", "category_id", "published_at", "pv", "status", "thum
b", "title", "user_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id" [{{2016, 1, 6}, {6, 15, 41, 0}
}, {{2016, 1, 6}, {6, 15, 41, 0}}, "<p>with Image Post</p><p>with Image Post</p>", 13, {{2016, 1, 1}, {0, 0, 0, 0}}, n
il, 2, nil, "with image post", nil] OK query=0.8ms
[debug] INSERT INTO "posts_tags" ("inserted_at", "updated_at", "post_id", "tag_id") VALUES ($1, $2, $3, $4) RETURNING
"id" [{{2016, 1, 6}, {6, 15, 41, 0}}, {{2016, 1, 6}, {6, 15, 41, 0}}, 9, 1] OK query=5.2ms
[debug] INSERT INTO "posts_tags" ("inserted_at", "updated_at", "post_id", "tag_id") VALUES ($1, $2, $3, $4) RETURNING
"id" [{{2016, 1, 6}, {6, 15, 41, 0}}, {{2016, 1, 6}, {6, 15, 41, 0}}, 9, 5] OK query=2.2ms
[debug] COMMIT [] OK query=3.0ms
[debug] BEGIN [] OK query=0.3ms
[debug] UPDATE "posts" SET "updated_at" = $1, "thumb" = $2 WHERE "id" = $3 [{{2016, 1, 6}, {6, 15, 41, 0}}, "www.dotup
.jpg?63619280141", 9] OK query=1.1ms
[debug] COMMIT [] OK query=4.4ms
[info] Sent 500 in 607ms
[error] #PID<0.1292.0> running Dera.Endpoint terminated
Server: vgt-phoenix:4000 (http)
Request: POST /admin/api/posts/
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function :ok.id/1 (module :ok is not available)
        :ok.id({:ok, %Dera.Post{__meta__: #Ecto.Schema.Metadata<:loaded>, author: #Ecto.Association.NotLoaded<association :author is not loaded>, body: "<p>with Image Post</p><p>with Image Post</p>", category: #Ecto.Association.NotLoaded<association :category is not loaded>, category_id: 13, id: 9, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, posts_tags: [%Dera.PostsTag{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 17, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, post: #Ecto.Association.NotLoaded<association :post is not loaded>, post_id: 9, tag: #Ecto.Association.NotLoaded<association :tag is not loaded>, tag_id: 1, updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}}, %Dera.PostsTag{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 18, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, post: #Ecto.Association.NotLoaded<association :post is not loaded>, post_id: 9, tag: #Ecto.Association.NotLoaded<association :tag is not loaded>, tag_id: 5, updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}}], pub
lished_at: #Ecto.DateTime<2016-01-01T00:00:00Z>, pv: nil, status: 2, tags: #Ecto.Association.NotLoaded<association :ta
gs is not loaded>, thumb: %{file_name: "www.dotup.jpg", updated_at: #Ecto.DateTime<2016-01-06T06:15:41Z>}, title: "wit
h image post", updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, secon
d: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0,
until: :max}, year: 2016}, user_id: nil}})
        (dera) Dera.Admin.Api.PostView.render/2
        (dera) web/views/admin/api/post_view.ex:9: Dera.Admin.Api.PostView.render/2
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (dera) web/controllers/admin/api/post_controller.ex:1: Dera.Admin.Api.PostController.action/2
        (dera) web/controllers/admin/api/post_controller.ex:1: Dera.Admin.Api.PostController.phoenix_controller_pipeli
ne/2
        (dera) lib/phoenix/router.ex:261: Dera.Router.dispatch/2
        (dera) web/router.ex:1: Dera.Router.do_call/2
        (dera) lib/dera/endpoint.ex:1: Dera.Endpoint.phoenix_pipeline/1
        (dera) lib/plug/debugger.ex:92: Dera.Endpoint."call (overridable 3)"/2
        (dera) lib/phoenix/endpoint/render_errors.ex:34: Dera.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
  Parameters: %{"_csrf_token" => "CDc2QRoQIQ8tey0WNDMsYTR2KQARJgAAguOtuULmJ4CgeTC9w/ahZQ==", "post" => %{"body" => "<p
>with Image Post</p><p>with Image Post</p>", "category_id" => "13", "posts_tags" => %{"0" => %{"tag_id" => "1"}, "1" =
> %{"tag_id" => "5"}}, "published_at" => %{"day" => "1", "hour" => "9", "min" => "0", "month" => "1", "year" => "2016"
}, "status" => "2", "thumb" => %Plug.Upload{content_type: "image/jpeg", filename: "www.dotup.jpg", path: "/tmp/plug-14
52/multipart-60941-221262-1"}, "title" => "with image post"}}
  Pipelines: [:api]
warning: casting assocs with cast/4 is deprecated, please use cast_assoc/3 instead
    (ecto) lib/ecto/changeset.ex:417: Ecto.Changeset.do_process_param/8
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (ecto) lib/ecto/changeset.ex:377: Ecto.Changeset.cast/5
[debug] BEGIN [] OK query=1.7ms queue=0.1ms
[debug] INSERT INTO "posts" ("inserted_at", "updated_at", "body", "category_id", "published_at", "pv", "status", "thum
b", "title", "user_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id" [{{2016, 1, 6}, {6, 15, 41, 0}
}, {{2016, 1, 6}, {6, 15, 41, 0}}, "<p>with Image Post</p><p>with Image Post</p>", 13, {{2016, 1, 1}, {0, 0, 0, 0}}, n
il, 2, nil, "with image post", nil] OK query=0.8ms
[debug] INSERT INTO "posts_tags" ("inserted_at", "updated_at", "post_id", "tag_id") VALUES ($1, $2, $3, $4) RETURNING
"id" [{{2016, 1, 6}, {6, 15, 41, 0}}, {{2016, 1, 6}, {6, 15, 41, 0}}, 9, 1] OK query=5.2ms
[debug] INSERT INTO "posts_tags" ("inserted_at", "updated_at", "post_id", "tag_id") VALUES ($1, $2, $3, $4) RETURNING
"id" [{{2016, 1, 6}, {6, 15, 41, 0}}, {{2016, 1, 6}, {6, 15, 41, 0}}, 9, 5] OK query=2.2ms
[debug] COMMIT [] OK query=3.0ms
[debug] BEGIN [] OK query=0.3ms
[debug] UPDATE "posts" SET "updated_at" = $1, "thumb" = $2 WHERE "id" = $3 [{{2016, 1, 6}, {6, 15, 41, 0}}, "www.dotup
.jpg?63619280141", 9] OK query=1.1ms
[debug] COMMIT [] OK query=4.4ms
[info] Sent 500 in 607ms
[error] #PID<0.1292.0> running Dera.Endpoint terminated
Server: vgt-phoenix:4000 (http)
Request: POST /admin/api/posts/
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function :ok.id/1 (module :ok is not available)
        :ok.id({:ok, %Dera.Post{__meta__: #Ecto.Schema.Metadata<:loaded>, author: #Ecto.Association.NotLoaded<association :author is not loaded>, body: "<p>with Image Post</p><p>with Image Post</p>", category: #Ecto.Association.NotLoaded<association :category is not loaded>, category_id: 13, id: 9, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, posts_tags: [%Dera.PostsTag{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 17, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, post: #Ecto.Association.NotLoaded<association :post is not loaded>, post_id: 9, tag: #Ecto.Association.NotLoaded<association :tag is not loaded>, tag_id: 1, updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}}, %Dera.PostsTag{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 18, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, post: #Ecto.Association.NotLoaded<association :post is not loaded>, post_id: 9, tag: #Ecto.Association.NotLoaded<association :tag is not loaded>, tag_id: 5, updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}}], pub
lished_at: #Ecto.DateTime<2016-01-01T00:00:00Z>, pv: nil, status: 2, tags: #Ecto.Association.NotLoaded<association :ta
gs is not loaded>, thumb: %{file_name: "www.dotup.jpg", updated_at: #Ecto.DateTime<2016-01-06T06:15:41Z>}, title: "wit
h image post", updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, secon
d: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0,
until: :max}, year: 2016}, user_id: nil}})
        (dera) Dera.Admin.Api.PostView.render/2
        (dera) web/views/admin/api/post_view.ex:9: Dera.Admin.Api.PostView.render/2
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (dera) web/controllers/admin/api/post_controller.ex:1: Dera.Admin.Api.PostController.action/2
        (dera) web/controllers/admin/api/post_controller.ex:1: Dera.Admin.Api.PostController.phoenix_controller_pipeli
ne/2
        (dera) lib/phoenix/router.ex:261: Dera.Router.dispatch/2
        (dera) web/router.ex:1: Dera.Router.do_call/2
        (dera) lib/dera/endpoint.ex:1: Dera.Endpoint.phoenix_pipeline/1
        (dera) lib/plug/debugger.ex:92: Dera.Endpoint."call (overridable 3)"/2
        (dera) lib/phoenix/endpoint/render_errors.ex:34: Dera.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4[debug] Processing by Dera.Admin.Api.PostController.create/2
  Parameters: %{"_csrf_token" => "CDc2QRoQIQ8tey0WNDMsYTR2KQARJgAAguOtuULmJ4CgeTC9w/ahZQ==", "post" => %{"body" => "<p
>with Image Post</p><p>with Image Post</p>", "category_id" => "13", "posts_tags" => %{"0" => %{"tag_id" => "1"}, "1" =
> %{"tag_id" => "5"}}, "published_at" => %{"day" => "1", "hour" => "9", "min" => "0", "month" => "1", "year" => "2016"
}, "status" => "2", "thumb" => %Plug.Upload{content_type: "image/jpeg", filename: "www.dotup.jpg", path: "/tmp/plug-14
52/multipart-60941-221262-1"}, "title" => "with image post"}}
  Pipelines: [:api]
warning: casting assocs with cast/4 is deprecated, please use cast_assoc/3 instead
    (ecto) lib/ecto/changeset.ex:417: Ecto.Changeset.do_process_param/8
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1151: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (ecto) lib/ecto/changeset.ex:377: Ecto.Changeset.cast/5
[debug] BEGIN [] OK query=1.7ms queue=0.1ms
[debug] INSERT INTO "posts" ("inserted_at", "updated_at", "body", "category_id", "published_at", "pv", "status", "thum
b", "title", "user_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id" [{{2016, 1, 6}, {6, 15, 41, 0}
}, {{2016, 1, 6}, {6, 15, 41, 0}}, "<p>with Image Post</p><p>with Image Post</p>", 13, {{2016, 1, 1}, {0, 0, 0, 0}}, n
il, 2, nil, "with image post", nil] OK query=0.8ms
[debug] INSERT INTO "posts_tags" ("inserted_at", "updated_at", "post_id", "tag_id") VALUES ($1, $2, $3, $4) RETURNING
"id" [{{2016, 1, 6}, {6, 15, 41, 0}}, {{2016, 1, 6}, {6, 15, 41, 0}}, 9, 1] OK query=5.2ms
[debug] INSERT INTO "posts_tags" ("inserted_at", "updated_at", "post_id", "tag_id") VALUES ($1, $2, $3, $4) RETURNING
"id" [{{2016, 1, 6}, {6, 15, 41, 0}}, {{2016, 1, 6}, {6, 15, 41, 0}}, 9, 5] OK query=2.2ms
[debug] COMMIT [] OK query=3.0ms
[debug] BEGIN [] OK query=0.3ms
[debug] UPDATE "posts" SET "updated_at" = $1, "thumb" = $2 WHERE "id" = $3 [{{2016, 1, 6}, {6, 15, 41, 0}}, "www.dotup
.jpg?63619280141", 9] OK query=1.1ms
[debug] COMMIT [] OK query=4.4ms
[info] Sent 500 in 607ms
[error] #PID<0.1292.0> running Dera.Endpoint terminated
Server: vgt-phoenix:4000 (http)
Request: POST /admin/api/posts/
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function :ok.id/1 (module :ok is not available)
        :ok.id({:ok, %Dera.Post{__meta__: #Ecto.Schema.Metadata<:loaded>, author: #Ecto.Association.NotLoaded<association :author is not loaded>, body: "<p>with Image Post</p><p>with Image Post</p>", category: #Ecto.Association.NotLoaded<association :category is not loaded>, category_id: 13, id: 9, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, posts_tags: [%Dera.PostsTag{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 17, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, post: #Ecto.Association.NotLoaded<association :post is not loaded>, post_id: 9, tag: #Ecto.Association.NotLoaded<association :tag is not loaded>, tag_id: 1, updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}}, %Dera.PostsTag{__meta__: #Ecto.Schema.Metadata<:loaded>, id: 18, inserted_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}, post: #Ecto.Association.NotLoaded<association :post is not loaded>, post_id: 9, tag: #Ecto.Association.NotLoaded<association :tag is not loaded>, tag_id: 5, updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, second: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0, until: :max}, year: 2016}}], pub
lished_at: #Ecto.DateTime<2016-01-01T00:00:00Z>, pv: nil, status: 2, tags: #Ecto.Association.NotLoaded<association :ta
gs is not loaded>, thumb: %{file_name: "www.dotup.jpg", updated_at: #Ecto.DateTime<2016-01-06T06:15:41Z>}, title: "wit
h image post", updated_at: %Timex.DateTime{calendar: :gregorian, day: 6, hour: 6, minute: 15, month: 1, ms: 0.0, secon
d: 41, timezone: %Timex.TimezoneInfo{abbreviation: "UTC", from: :min, full_name: "UTC", offset_std: 0, offset_utc: 0,
until: :max}, year: 2016}, user_id: nil}})
        (dera) Dera.Admin.Api.PostView.render/2
        (dera) web/views/admin/api/post_view.ex:9: Dera.Admin.Api.PostView.render/2
        (phoenix) lib/phoenix/view.ex:344: Phoenix.View.render_to_iodata/3
        (phoenix) lib/phoenix/controller.ex:633: Phoenix.Controller.do_render/4
        (dera) web/controllers/admin/api/post_controller.ex:1: Dera.Admin.Api.PostController.action/2
        (dera) web/controllers/admin/api/post_controller.ex:1: Dera.Admin.Api.PostController.phoenix_controller_pipeli
ne/2
        (dera) lib/phoenix/router.ex:261: Dera.Router.dispatch/2
        (dera) web/router.ex:1: Dera.Router.do_call/2
        (dera) lib/dera/endpoint.ex:1: Dera.Endpoint.phoenix_pipeline/1
        (dera) lib/plug/debugger.ex:92: Dera.Endpoint."call (overridable 3)"/2
        (dera) lib/phoenix/endpoint/render_errors.ex:34: Dera.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by igrs** [comment]
おそらく
[これ](https://github.com/ali-inc/dera/commit/afbd8c4a7f1bd9b9631c6504cf3d809d3d973df2)で大丈夫なはずです。

**Comment by kaave** [comment]
確認とれました :+1:
